#!/bin/bash

VERSION=`./version.py`

./features/configure_cape_universal/configure_pins.sh
cp ./features/configure_cape_universal/versions/$VERSION/overlay.inc ./features/configure_cape_universal/overlay.inc
