#!/bin/bash

if dpkg-query -s liblockfile-bin | grep "install ok installed"; then
  echo 'liblockfile-bin alread installed'
else
  sudo dpkg -i /home/pocketnc/pocketnc/Settings/features/usb_drive/liblockfile-bin_1.16-1.1_armhf.deb
  sudo apt-get install -f
fi

if dpkg-query -s liblockfile1 | grep "install ok installed"; then
  echo 'liblockfile1 alread installed'
else
  sudo dpkg -i /home/pocketnc/pocketnc/Settings/features/usb_drive/liblockfile1_1.16-1.1_armhf.deb
  sudo apt-get install -f
fi

if dpkg-query -s lockfile-progs | grep "install ok installed"; then
  echo 'lockfile-progs already installed'
else
  sudo dpkg -i /home/pocketnc/pocketnc/Settings/features/usb_drive/lockfile-progs_0.1.17+b1_armhf.deb
  sudo apt-get install -f
fi

if dpkg-query -s usbmount | grep "install ok installed"; then
  echo 'usbmount already installed'
else
  if uname -r | grep 3.8-1; then
    sudo dpkg -i /home/pocketnc/pocketnc/Settings/features/usb_drive/usbmount_0.0.22_all.deb
  else
    sudo dpkg -i /home/pocketnc/pocketnc/Settings/features/usb_drive/usbmount_0.0.24_all.deb
  fi
  sudo apt-get install -f
fi

