#!/usr/bin/python3

import os
import subprocess

POCKETNC_DIRECTORY = "/home/pocketnc/pocketnc"
FEATURES_DIR = os.path.join(POCKETNC_DIRECTORY, "Settings/features")

for feature in os.listdir(FEATURES_DIR):
  feature_path = os.path.join(FEATURES_DIR, feature)
  detect_path = os.path.join(feature_path, "detect")
  post_update_path = os.path.join(feature_path, "postUpdate")

  if os.path.isfile(detect_path):
    detect = subprocess.check_output([ detect_path ]).strip().decode("utf-8")
    if detect == "1" and os.path.isfile(post_update_path):
      print("Executing postUpdate for feature, %s" % feature)
      print(post_update_path)
      subprocess.check_output([ post_update_path ])
