#!/usr/bin/python 

import os
import subprocess
import sys

POCKETNC_DIRECTORY = "/home/pocketnc/pocketnc"
FEATURES_DIR = os.path.join(POCKETNC_DIRECTORY, "Settings/features")

for feature in os.listdir(FEATURES_DIR):
  feature_path = os.path.join(FEATURES_DIR, feature)
  detect_path = os.path.join(feature_path, "detect")
  pre_update_path = os.path.join(feature_path, "preUpdate")

  if os.path.isfile(detect_path):
    detect = subprocess.check_output([ detect_path ]).strip()
    if detect == "1" and os.path.isfile(pre_update_path):
      print "Executing preUpdate for feature, %s" % feature
      p = subprocess.check_output([ pre_update_path, sys.argv[1] ])
