from _typeshed import Incomplete

CONFIGPATH: Incomplete
CONFIGDIR: Incomplete
JOGJOINT: int
JOGTELEOP: int
inifile: Incomplete
trajcoordinates: Incomplete
jointcount: Incomplete
DBG_state: int

def DBG(str) -> None: ...
def load_handlers(usermod, halcomp, builder, commands, master): ...

class Trampoline:
    methods: Incomplete
    def __init__(self, methods) -> None: ...
    def __call__(self, *a, **kw) -> None: ...

class CNC_COMMANDS:
    emc: Incomplete
    emcstat: Incomplete
    emccommand: Incomplete
    return_to_mode: int
    sb: int
    jog_velocity: Incomplete
    angular_jog_velocity: Incomplete
    isjogging: Incomplete
    restart_line_number: int
    def __init__(self, master) -> None: ...
    def mdi_active(self, wname, m) -> None: ...
    def mist_on(self, wname, b) -> None: ...
    def mist_off(self, wname, b) -> None: ...
    def flood_on(self, wname, b) -> None: ...
    def flood_off(self, wname, b) -> None: ...
    def estop(self, wname, b) -> None: ...
    def estop_reset(self, wname, b) -> None: ...
    def machine_off(self, wname, b) -> None: ...
    def machine_on(self, wname, b) -> None: ...
    def home_all(self, wname, b) -> None: ...
    def unhome_all(self, wname, b) -> None: ...
    def home_selected(self, wname, joint) -> None: ...
    def unhome_selected(self, wname, joint) -> None: ...
    def jogging(self, wname, b) -> None: ...
    def override_limits(self, wname, b) -> None: ...
    def spindle_forward_adjust(self, wname, rpm: int = ...) -> None: ...
    def spindle_forward(self, wname, rpm: int = ...) -> None: ...
    def spindle_stop(self, wname, b) -> None: ...
    def spindle_reverse(self, wname, rpm: int = ...) -> None: ...
    def spindle_reverse_adjust(self, wname, rpm: int = ...) -> None: ...
    def spindle_faster(self, wname, b) -> None: ...
    def spindle_slower(self, wname, b) -> None: ...
    def set_linear_jog_velocity(self, wname, cmd) -> None: ...
    def set_angular_jog_velocity(self, wname, cmd) -> None: ...
    def continuous_jog(self, wname, cmd) -> None: ...
    def incremental_jog(self, wname, cmd) -> None: ...
    def quill_up(self, wname, cmd) -> None: ...
    def feed_hold(self, wname, cmd) -> None: ...
    def feed_override(self, wname, f) -> None: ...
    def rapid_override(self, wname, f) -> None: ...
    def spindle_override(self, wname, s) -> None: ...
    def max_velocity(self, wname, m) -> None: ...
    def reload_tooltable(self, wname, b) -> None: ...
    def optional_stop(self, wname, cmd) -> None: ...
    def block_delete(self, wname, cmd) -> None: ...
    def abort(self, wname, cmd: Incomplete | None = ...) -> None: ...
    def pause(self, wname, cmd: Incomplete | None = ...) -> None: ...
    def resume(self, wname, cmd: Incomplete | None = ...) -> None: ...
    def single_block(self, wname, s) -> None: ...
    def smart_cycle_start(self, wname, cmd: Incomplete | None = ...) -> None: ...
    def re_start(self, wname, line) -> None: ...
    def mdi_and_return(self, wname, cmd) -> None: ...
    def mdi(self, wname, cmd) -> None: ...
    restart_reset_line: Incomplete
    def set_restart_line(self, wname, line, reset: int = ...) -> None: ...
    def set_manual_mode(self) -> None: ...
    def set_mdi_mode(self) -> None: ...
    def set_auto_mode(self) -> None: ...
    def get_mode(self): ...
    def ok_for_mdi(self): ...
    def is_spindle_running(self): ...
    def periodic(self) -> None: ...
    def __getitem__(self, item): ...
    def __setitem__(self, item, value): ...
    def get_jjogmode(self): ...
    def jnum_for_axisnum(self, axisnum): ...
    def get_jog_info(self, axisnum): ...
