from _typeshed import Incomplete
from pyui import commands as commands

CONFIGPATH: Incomplete
CONFIGDIR: Incomplete
P: str
R: str
DBG_state: int

def DBG(str, level: int = ...) -> None: ...

class keyboard:
    filename: Incomplete
    def __init__(self, filename=...) -> None: ...
    def validate(self) -> None: ...
    hal: Incomplete
    widgets: Incomplete
    r_c: Incomplete
    config: Incomplete
    cmd: Incomplete
    def build(self, dbg_state: int = ...) -> None: ...
    def update(self, *arg) -> None: ...
    def periodic(self) -> None: ...
    def exit(self) -> None: ...
    def __getitem__(self, item): ...
    def __setitem__(self, item, value) -> None: ...

def main() -> None: ...
