from _hal import *
import _hal
from _typeshed import Incomplete

class _ItemWrap:
    def __new__(cls, item): ...
    def __init__(self, item) -> None: ...
    name: Incomplete
    type: Incomplete
    dir: Incomplete
    value: Incomplete

class Pin(_ItemWrap):
    def __init__(self, item) -> None: ...

class Param(_ItemWrap):
    def __init__(self, item) -> None: ...

class component(_hal.component):
    def newpin(self, *a, **kw): ...
    def newparam(self, *a, **kw): ...
    def getpin(self, *a, **kw): ...
    def getparam(self, *a, **kw): ...
